-- traffgen-stats D1 schema
-- Apply with:
--   wrangler d1 execute traffgen-stats --remote --file=./schema.sql
-- Safe to re-run; uses CREATE TABLE IF NOT EXISTS everywhere.

-- One row per install (anonymous UUID from the client).
CREATE TABLE IF NOT EXISTS installs (
  id          TEXT PRIMARY KEY,           -- UUIDv4 generated client-side
  first_seen  INTEGER NOT NULL,           -- unix epoch seconds
  last_seen   INTEGER NOT NULL,           -- unix epoch seconds
  version     TEXT,
  arch        TEXT,                       -- amd64 | arm64 | arm/v7
  os_family   TEXT,                       -- ubuntu | debian | rocky | rpi | other
  country     TEXT,                       -- ISO-3166-1 alpha-2 from cf.country header
  created_ip_hash TEXT                    -- sha256(client_ip + DAILY_SALT) — for abuse caps only
);
CREATE INDEX IF NOT EXISTS idx_installs_last_seen ON installs(last_seen);
CREATE INDEX IF NOT EXISTS idx_installs_version   ON installs(version);
CREATE INDEX IF NOT EXISTS idx_installs_country   ON installs(country);

-- Global single-row counters.  Always operate on id=1.
CREATE TABLE IF NOT EXISTS counters (
  id              INTEGER PRIMARY KEY CHECK (id = 1),
  tests_run       INTEGER NOT NULL DEFAULT 0,
  runtime_seconds INTEGER NOT NULL DEFAULT 0,
  updated_at      INTEGER NOT NULL DEFAULT 0
);
INSERT OR IGNORE INTO counters (id, tests_run, runtime_seconds, updated_at)
VALUES (1, 0, 0, 0);

-- Per-suite popularity (lifetime).
CREATE TABLE IF NOT EXISTS suite_counts (
  suite TEXT PRIMARY KEY,
  count INTEGER NOT NULL DEFAULT 0
);

-- Per-version active install counts (recomputed by cron).
CREATE TABLE IF NOT EXISTS version_counts (
  version TEXT PRIMARY KEY,
  count   INTEGER NOT NULL DEFAULT 0
);

-- Daily Docker Hub pull snapshots (cron-populated).
CREATE TABLE IF NOT EXISTS docker_pulls (
  date  TEXT PRIMARY KEY,           -- YYYY-MM-DD (UTC)
  pulls INTEGER NOT NULL
);

-- Hybrid seed — edit values via:
--   wrangler d1 execute traffgen-stats --remote --command \
--     "INSERT OR REPLACE INTO seed(key,value) VALUES('baseline_tests','4000000');"
CREATE TABLE IF NOT EXISTS seed (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- Per-IP abuse counters (resets daily via cron).
CREATE TABLE IF NOT EXISTS abuse_installs_today (
  ip_hash TEXT PRIMARY KEY,
  count   INTEGER NOT NULL DEFAULT 0,
  date    TEXT NOT NULL                  -- YYYY-MM-DD
);

-- Cached /v1/stats JSON blob (regenerated by cron + on cache miss).
CREATE TABLE IF NOT EXISTS stats_cache (
  id         INTEGER PRIMARY KEY CHECK (id = 1),
  payload    TEXT NOT NULL,
  generated_at INTEGER NOT NULL
);
